apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: se-symposium-backend
  name: ora-se-symposium-backend
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: se-symposium-backend
        tier: backend
    spec:
      containers:
        - name: ora-se-symposium-backend
          image: vamsiramakrishnan/ora-se-symposium-backend:${WERCKER_GIT_BRANCH}-${WERCKER_GIT_COMMIT} 
          ports:
          - containerPort: 4000
            protocol: TCP
---


apiVersion: v1
kind: Service
metadata:
  labels:
    app: se-symposium-backend
  name: ora-se-symposium-backend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 4000
  selector:
    app: se-symposium-backend
    tier: backend
  sessionAffinity: None
  type: LoadBalancer
